languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "http://karampok.me"
canonifyurls = true
title = "karampok"
author = "Konstantinos Karampogias"

[indexes]
   category = "categories"
   tag = "tags"
   other = "other"
[Params]
  AuthorName = "Konstantinos"
  github = "karampok"
  twitter = "karampok"
  email = "karampok+site@gmail.com"
  description = "It’s hardware that makes a machine fast. It’s software that makes a fast machine slow."
  cv = "/resume/cv"
  about = "/pages/about"
  muut = "karampok"
  linkedin = "kkarampogias"
  cover = "/images/background-4.jpg"
  logo = "/images/logo-1.jpg"
